# Generated by Django 2.2.14 on 2020-12-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
