# Generated by Django 2.2.14 on 2020-12-14 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='upload',
            field=models.FileField(upload_to='file/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['csv', 'pdf', 'txt'])]),
        ),
    ]
